vich_uploader:
    db_driver: orm
    twig: false

    mappings:
       user_avatar:
           uri_prefix: /uploads/users
           upload_destination: '%kernel.project_dir%/public/uploads/users'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

       book_front_cover:
           uri_prefix: /uploads/front_cover
           upload_destination: '%kernel.project_dir%/public/uploads/front_cover'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

       book_back_cover:
           uri_prefix: /uploads/back_cover
           upload_destination: '%kernel.project_dir%/public/uploads/back_cover'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
